source 'https://github.com/clearent/CocoaPods.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'ExampleSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ClearentIdtechIOSFrameworkPod', '4.0.48' 
  # Pods for ExampleSwift
end
