source 'https://github.com/clearent/CocoaPods.git'
source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '13.0'

target 'ObjC-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjC-Example
  pod 'ClearentIdtechIOSFrameworkPod', '4.0.61'
end
